### ISSUE TITLE
Games other than Starcraft, Warcraft III, and Diablo II

### ISSUE THREAD

**Issue by eband** [pvpgn/battle.net-gateway-installer#1]
For games that are other than Starcraft, Warcraft III, and Diablo II, how would I configure the BAT file so that the server is added?

I am trying to play on a Warcraft II: Battle.NET Edition Server.

**Comment by HarpyWar** [comment]
Warcraft 2 reads Battle.net server settings in the same way as Starcraft.

**Comment by eband** [comment]
What about the first Diablo?

**Comment by HarpyWar** [comment]
Starcraft / Warcraft 2 / Diablo 1 use the same registry key.
